# Generated by Django 4.1.5 on 2023-02-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpmbParking', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.TextField(default=models.CharField(max_length=11, primary_key=True, serialize=False))),
                ('studentName', models.TextField()),
                ('plateNo', models.CharField(default='Null', max_length=7)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpmbParking.class')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpmbParking.course')),
            ],
        ),
    ]
