# Generated by Django 4.1.5 on 2023-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpmbParking', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parkingID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('availability', models.CharField(max_length=13)),
            ],
        ),
    ]
