# Generated by Django 4.1.5 on 2023-02-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpmbParking', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('reviewDescription', models.TextField()),
                ('reviewDate', models.DateField()),
                ('reviewTime', models.TimeField()),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpmbParking.booking')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpmbParking.student')),
            ],
        ),
    ]
